### Register
POST http://localhost:3000/v1/auth/register
Content-Type: application/json

{
  "email": "test1@gmail.com",
  "password": "Password1!",
  "name": "Bret Axl Sebastian"
}

### Login
POST http://localhost:3000/v1/auth/login
Content-Type: application/json

{
  "email": "test1@gmail.com",
  "password": "Password1!"
}

### Get All Users
GET http://localhost:3000/v1/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTkzNjJkMjM0MTUyYzc3YTg0YTUwZGEiLCJpYXQiOjE3MDQ5NTI1NDgsImV4cCI6MTcwNjc1MjU0OCwidHlwZSI6ImFjY2VzcyJ9.pGHrWUymLB2-qRW-iW5Xx1NN6E9FnlaCtqzZReiHw8g

### Get Current User Data
GET http://localhost:3000/v1/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTkzNjJkMjM0MTUyYzc3YTg0YTUwZGEiLCJpYXQiOjE3MDQ5NTI1NDgsImV4cCI6MTcwNjc1MjU0OCwidHlwZSI6ImFjY2VzcyJ9.pGHrWUymLB2-qRW-iW5Xx1NN6E9FnlaCtqzZReiHw8g

### Get Dividers
GET http://localhost:3000/v1/dividers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTkzNjJkMjM0MTUyYzc3YTg0YTUwZGEiLCJpYXQiOjE3MDQ5NTI1NDgsImV4cCI6MTcwNjc1MjU0OCwidHlwZSI6ImFjY2VzcyJ9.pGHrWUymLB2-qRW-iW5Xx1NN6E9FnlaCtqzZReiHw8g

### Get Divider by id
GET http://localhost:3000/v1/dividers/6546cee77562caa6b35df5a9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTkzNjJkMjM0MTUyYzc3YTg0YTUwZGEiLCJpYXQiOjE3MDQ5NTI1NDgsImV4cCI6MTcwNjc1MjU0OCwidHlwZSI6ImFjY2VzcyJ9.pGHrWUymLB2-qRW-iW5Xx1NN6E9FnlaCtqzZReiHw8g

### Create a Divider
POST http://localhost:3000/v1/dividers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTkzNjJkMjM0MTUyYzc3YTg0YTUwZGEiLCJpYXQiOjE3MDQ5NTI1NDgsImV4cCI6MTcwNjc1MjU0OCwidHlwZSI6ImFjY2VzcyJ9.pGHrWUymLB2-qRW-iW5Xx1NN6E9FnlaCtqzZReiHw8g

{
  "name": "Development"
}

### Get Subjects
GET http://localhost:3000/v1/subjects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTkzNjJkMjM0MTUyYzc3YTg0YTUwZGEiLCJpYXQiOjE3MDQ5NTI1NDgsImV4cCI6MTcwNjc1MjU0OCwidHlwZSI6ImFjY2VzcyJ9.pGHrWUymLB2-qRW-iW5Xx1NN6E9FnlaCtqzZReiHw8g

### Create a Subject
POST http://localhost:3000/v1/subjects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTkzNjJkMjM0MTUyYzc3YTg0YTUwZGEiLCJpYXQiOjE3MDQ5NTI1NDgsImV4cCI6MTcwNjc1MjU0OCwidHlwZSI6ImFjY2VzcyJ9.pGHrWUymLB2-qRW-iW5Xx1NN6E9FnlaCtqzZReiHw8g

{
  "divider": "654831a876286e1720a96387",
  "name": "Sample",
  "colorHex": "ff0000"
}

### Create a PDF Note
POST http://localhost:3000/v1/notes/pdf
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTkzNjJkMjM0MTUyYzc3YTg0YTUwZGEiLCJpYXQiOjE3MDQ5NTI1NDgsImV4cCI6MTcwNjc1MjU0OCwidHlwZSI6ImFjY2VzcyJ9.pGHrWUymLB2-qRW-iW5Xx1NN6E9FnlaCtqzZReiHw8g

{
  "title": "Flame of Recca",
  "url": "https://devx-images.s3.ap-southeast-1.amazonaws.com/flame.pdf",
  "subject": "654832a576286e1720a96396"
}

### Get Notes
GET http://localhost:3000/v1/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTZjMjBhMmZkZDVkYjA4NmRjMDVkNzYiLCJpYXQiOjE3MDE1ODg4MjAsImV4cCI6MTcwMzM4ODgyMCwidHlwZSI6ImFjY2VzcyJ9.Et8UiktiFeLjfI-1GtR-KtxAVp1usxVDQQT66lDsgXg

### Create a Text Note
POST http://localhost:3000/v1/notes/text
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTkzNjJkMjM0MTUyYzc3YTg0YTUwZGEiLCJpYXQiOjE3MDQ5NTI1NDgsImV4cCI6MTcwNjc1MjU0OCwidHlwZSI6ImFjY2VzcyJ9.pGHrWUymLB2-qRW-iW5Xx1NN6E9FnlaCtqzZReiHw8g

{
  "transcription": "I am the main character of my story. I am Sedrick Reyes! I am 24 years old",
  "title": "Dan Sedrick",
  "subject": "654832a576286e1720a96396"
}

### Create a Video Note
POST http://localhost:3000/v1/notes/video
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTkzNjJkMjM0MTUyYzc3YTg0YTUwZGEiLCJpYXQiOjE3MDQ5NTI1NDgsImV4cCI6MTcwNjc1MjU0OCwidHlwZSI6ImFjY2VzcyJ9.pGHrWUymLB2-qRW-iW5Xx1NN6E9FnlaCtqzZReiHw8g

{
  "title": "Joseph Prince",
  "url": "https://devx-images.s3.ap-southeast-1.amazonaws.com/Joseph+Prince+-+The+Lord+makes+your+brokenness+beautiful.mp4",
  "subject": "654832a576286e1720a96396"
}

### Create a URL Note
POST http://localhost:3000/v1/notes/url
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTkzNjJkMjM0MTUyYzc3YTg0YTUwZGEiLCJpYXQiOjE3MDQ5NTI1NDgsImV4cCI6MTcwNjc1MjU0OCwidHlwZSI6ImFjY2VzcyJ9.pGHrWUymLB2-qRW-iW5Xx1NN6E9FnlaCtqzZReiHw8g

{
  "title": "final fantasy",
  "url": "https://en.wikipedia.org/wiki/Final_Fantasy",
  "subject": "654832a576286e1720a96396"
}

### Create a Youtube Note
POST http://localhost:3000/v1/notes/youtube
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTkzNjJkMjM0MTUyYzc3YTg0YTUwZGEiLCJpYXQiOjE3MDQ5NTI1NDgsImV4cCI6MTcwNjc1MjU0OCwidHlwZSI6ImFjY2VzcyJ9.pGHrWUymLB2-qRW-iW5Xx1NN6E9FnlaCtqzZReiHw8g

{
  "title": "Youtube",
  "url": "https://www.youtube.com/watch?v=zUhs-MWoTbg",
  "subject": "654832a576286e1720a96396"
}

### QUERY A note
POST http://localhost:3000/v1/notes/query
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTkzNjJkMjM0MTUyYzc3YTg0YTUwZGEiLCJpYXQiOjE3MDQ5NTI1NDgsImV4cCI6MTcwNjc1MjU0OCwidHlwZSI6ImFjY2VzcyJ9.pGHrWUymLB2-qRW-iW5Xx1NN6E9FnlaCtqzZReiHw8g

{
  "id": "654833ed8e981e18813d07cf",
  "query": "what is the latest in the series?"
}

### Chat A note
POST http://localhost:3000/v1/notes/chat
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTkzNjJkMjM0MTUyYzc3YTg0YTUwZGEiLCJpYXQiOjE3MDQ5NTI1NDgsImV4cCI6MTcwNjc1MjU0OCwidHlwZSI6ImFjY2VzcyJ9.pGHrWUymLB2-qRW-iW5Xx1NN6E9FnlaCtqzZReiHw8g

{
  "id": "6549a9ae1a9ba8b652adc36a",
  "question": "what is the latest in the series?"
}

### Get messages
GET http://localhost:3000/v1/messages?limit=200
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTkzNjJkMjM0MTUyYzc3YTg0YTUwZGEiLCJpYXQiOjE3MDQ5NTI1NDgsImV4cCI6MTcwNjc1MjU0OCwidHlwZSI6ImFjY2VzcyJ9.pGHrWUymLB2-qRW-iW5Xx1NN6E9FnlaCtqzZReiHw8g

