const voices = [
  {
    voice_id: '131a436c47064f708210df6628ef8f32',
    labels: ['Youth', 'Ads', 'Explainer', 'E-learning'],
    language: 'English',
    flag: 'https://static.heygencdn.com/region_flags/us.png',
    locale: 'en-US',
    sort: 36,
    gender: 'Female',
    tags: 'Young Adult, Ads, Explainer Videos, E-learning & Presentations',
    display_name: 'Amber - Friendly',
    preview: {
      movio: 'https://static.heygencdn.com/voice_preview/5HHGT48B6g6aSg2buYcBvw.wav',
    },
    settings: {
      style: '',
      elevenlabs_settings: null,
    },
    ssml: {
      style: [],
      lang: [],
      break: true,
      prosody: ['rate', 'pitch'],
      emphasis: 'none',
      say_as: [],
    },
    is_customer: false,
    is_favorite: false,
    is_paid: false,
    support_realtime: true,
  },
  {
    voice_id: '1ae3be1e24894ccabdb4d8139399f721',
    labels: ['Middle-Aged', 'E-learning', 'Audiobooks'],
    language: 'English',
    flag: 'https://static.heygencdn.com/region_flags/us.png',
    locale: 'en-US',
    sort: 1,
    gender: 'Male',
    tags: 'Middle-Age,E-learning & Presentations, Product demos, Explainer Videos, News, Ads',
    display_name: 'Tony - Professional',
    preview: {
      movio: 'https://static.heygencdn.com/voice_preview/LQUcrBcVHDMCSP5cX93CVd.wav',
    },
    settings: {
      style: 'general',
      elevenlabs_settings: null,
    },
    ssml: {
      style: [],
      lang: [],
      break: true,
      prosody: ['rate', 'pitch'],
      emphasis: 'none',
      say_as: [],
    },
    is_customer: false,
    is_favorite: false,
    is_paid: false,
    support_realtime: true,
  },
  {
    voice_id: '1bd001e7e50f421d891986aad5158bc8',
    labels: ['Youth', 'E-learning', 'Ads', 'Explainer'],
    language: 'English',
    flag: 'https://static.heygencdn.com/region_flags/us.png',
    locale: 'en-US',
    sort: 2,
    gender: 'Female',
    tags: 'Young Adult, Customer Service, Explainer Videos, Cheerful',
    display_name: 'Sara - Cheerful',
    preview: {
      movio: 'https://static.heygencdn.com/voice_preview/func8CFnfVLKF2VzGDCDCR.wav',
    },
    settings: {
      style: 'cheerful',
      elevenlabs_settings: null,
    },
    ssml: {
      style: [],
      lang: [],
      break: true,
      prosody: ['rate', 'pitch'],
      emphasis: 'none',
      say_as: [],
    },
    is_customer: false,
    is_favorite: false,
    is_paid: false,
    support_realtime: true,
  },
  {
    voice_id: '1fe966a9dfa14b16ab4d146fabe868b5',
    labels: ['Child', 'Audiobooks', 'Ads', 'Games'],
    language: 'English',
    flag: 'https://static.heygencdn.com/region_flags/us.png',
    locale: 'en-US',
    sort: 21,
    gender: 'Female',
    tags: 'Child, Audiobooks',
    display_name: 'Ana - Cheerful',
    preview: {
      movio: 'https://static.heygencdn.com/voice_preview/T4MYTkhp7F5SA9HRXHzL9A.wav',
    },
    settings: {
      style: '',
      elevenlabs_settings: null,
    },
    ssml: {
      style: [],
      lang: [],
      break: true,
      prosody: ['rate', 'pitch'],
      emphasis: 'none',
      say_as: [],
    },
    is_customer: false,
    is_favorite: false,
    is_paid: false,
    support_realtime: true,
  },
  {
    voice_id: '285900cdfd1641e0b163e97a96973212',
    labels: ['Youth', 'Ads', 'E-learning', 'Explainer'],
    language: 'English',
    flag: 'https://static.heygencdn.com/region_flags/us.png',
    locale: 'en-US',
    sort: 16,
    gender: 'Female',
    tags: 'Young Adult, E-learning & Presentations, Product demos, Explainer Videos, News, Ads',
    display_name: 'Monica - Calm',
    preview: {
      movio: 'https://static.heygencdn.com/voice_preview/A28mKDAgwgmKD8KdG68rkZ.wav',
    },
    settings: {
      style: '',
      elevenlabs_settings: null,
    },
    ssml: {
      style: [],
      lang: [],
      break: true,
      prosody: ['rate', 'pitch'],
      emphasis: 'none',
      say_as: [],
    },
    is_customer: false,
    is_favorite: false,
    is_paid: false,
    support_realtime: true,
  },
  {
    voice_id: '2f72ee82b83d4b00af16c4771d611752',
    labels: ['Youth', 'Explainer', 'Narration', 'E-learning'],
    language: 'English',
    flag: 'https://static.heygencdn.com/region_flags/us.png',
    locale: 'en-US',
    sort: 1,
    gender: 'Female',
    tags: 'Young Adult, Customer Service',
    display_name: 'Jenny - Professional',
    preview: {
      movio: 'https://static.heygencdn.com/voice_preview/XTyya7QKzhwvwDrVQLTvoQ.wav',
    },
    settings: {
      style: 'customerservice',
      elevenlabs_settings: null,
    },
    ssml: {
      style: [],
      lang: [],
      break: true,
      prosody: ['rate', 'pitch'],
      emphasis: 'none',
      say_as: [],
    },
    is_customer: false,
    is_favorite: false,
    is_paid: false,
    support_realtime: true,
  },
  {
    voice_id: '3fbd2cac3ddd4c109e17296e324845ec',
    labels: ['Older', 'Audiobooks', 'Narration', 'E-learning', 'Ads'],
    language: 'English',
    flag: 'https://static.heygencdn.com/region_flags/us.png',
    locale: 'en-US',
    sort: 20,
    gender: 'Male',
    tags: 'Middle-Age,E-learning & Presentations, Product demos, Explainer Videos, News, Ads',
    display_name: 'Delbert - Cheerful',
    preview: {
      movio: 'https://static.heygencdn.com/voice_preview/CMr49SZRNaARsvmJ3tGDsN.wav',
    },
    settings: {
      style: 'cheerful',
      elevenlabs_settings: null,
    },
    ssml: {
      style: [],
      lang: [],
      break: true,
      prosody: ['rate', 'pitch'],
      emphasis: 'none',
      say_as: [],
    },
    is_customer: false,
    is_favorite: false,
    is_paid: false,
    support_realtime: true,
  },
  {
    voice_id: '456e13f3ff1345d3b7ab0435ce024dc7',
    labels: ['Youth', 'Ads', 'Explainer'],
    language: 'English',
    flag: 'https://static.heygencdn.com/region_flags/us.png',
    locale: 'en-US',
    sort: 22,
    gender: 'Female',
    tags: 'Young Adult, Cheerful, Youtube, Customer Service',
    display_name: 'Isabella - Cheerful',
    preview: {
      movio: 'https://static.heygencdn.com/voice_preview/KhiBp6E75AmiqR2F9Ssmj7.wav',
    },
    settings: {
      style: 'Cheerful',
      elevenlabs_settings: null,
    },
    ssml: {
      style: [],
      lang: [],
      break: true,
      prosody: ['rate', 'pitch'],
      emphasis: 'none',
      say_as: [],
    },
    is_customer: false,
    is_favorite: false,
    is_paid: false,
    support_realtime: true,
  },
  {
    voice_id: '575a8643634944a28761fcd34331d3fa',
    labels: ['Youth'],
    language: 'English',
    flag: 'https://static.heygencdn.com/region_flags/us.png',
    locale: 'en-US',
    sort: 100,
    gender: 'male',
    tags: '',
    display_name: 'Dennis - Cheerful',
    preview: {
      movio: 'https://static.heygencdn.com/voice_preview/YpfMSycEaGKLyWZffnKsc7.mp3',
    },
    settings: {
      style: '',
      elevenlabs_settings: null,
    },
    ssml: {
      style: [],
      lang: [],
      break: true,
      prosody: ['rate'],
      emphasis: 'none',
      say_as: [],
    },
    is_customer: false,
    is_favorite: false,
    is_paid: false,
    support_realtime: false,
  },
  {
    voice_id: '6e7404e25c4b4385b04b0e2704c861c8',
    labels: ['Middle-Aged', 'Ads', 'Audiobooks', 'Narration'],
    language: 'English',
    flag: 'https://static.heygencdn.com/region_flags/us.png',
    locale: 'en-US',
    sort: 15,
    gender: 'Female',
    tags: '',
    display_name: 'Michelle - Natural',
    preview: {
      movio: 'https://static.heygencdn.com/voice_preview/djxEBTVHKLgXsJpb6ZrBVn.wav',
    },
    settings: {
      style: 'general',
      elevenlabs_settings: null,
    },
    ssml: {
      style: [],
      lang: [],
      break: true,
      prosody: ['rate', 'pitch'],
      emphasis: 'none',
      say_as: [],
    },
    is_customer: false,
    is_favorite: false,
    is_paid: false,
    support_realtime: true,
  },
  {
    voice_id: '76955c80188a4c149df169b5dc9e1a3a',
    labels: ['Youth', 'Explainer', 'E-learning', 'Audiobooks'],
    language: 'English',
    flag: 'https://static.heygencdn.com/region_flags/us.png',
    locale: 'en-US',
    sort: 12,
    gender: 'Female',
    tags: 'Young Adult, Assistant',
    display_name: 'Emma - Newscaster',
    preview: {
      movio: 'https://static.heygencdn.com/voice_preview/c3NuQJ7QnFRXFq8Kn4quwk.wav',
    },
    settings: {
      style: 'assistant',
      elevenlabs_settings: null,
    },
    ssml: {
      style: [],
      lang: [],
      break: true,
      prosody: ['rate', 'pitch'],
      emphasis: 'none',
      say_as: [],
    },
    is_customer: false,
    is_favorite: false,
    is_paid: false,
    support_realtime: true,
  },
  {
    voice_id: '932643d355ed4a3d837370a3068bbd1b',
    labels: ['Youth', 'Ads', 'Narration', 'Audiobooks'],
    language: 'English',
    flag: 'https://static.heygencdn.com/region_flags/us.png',
    locale: 'en-US',
    sort: 18,
    gender: 'Female',
    tags: 'Young Adult, Ads, Explainer Videos, E-learning & Presentations',
    display_name: 'Josie - Cheerful',
    preview: {
      movio: 'https://static.heygencdn.com/voice_preview/9SGYr6Xk7SUB8CMzR9rkHF.wav',
    },
    settings: {
      style: 'cheerful',
      elevenlabs_settings: null,
    },
    ssml: {
      style: [],
      lang: [],
      break: true,
      prosody: ['rate', 'pitch'],
      emphasis: 'none',
      say_as: [],
    },
    is_customer: false,
    is_favorite: false,
    is_paid: false,
    support_realtime: true,
  },
  {
    voice_id: 'a6f3eea9f3764d36a279ae810d1353c6',
    labels: ['Middle-Aged', 'Explainer', 'Audiobooks', 'Ads'],
    language: 'English',
    flag: 'https://static.heygencdn.com/region_flags/us.png',
    locale: 'en-US',
    sort: 18,
    gender: 'Male',
    tags: 'Middle-Age,E-learning & Presentations, Product demos, Explainer Videos, News, Ads',
    display_name: 'Tracy - Cheerful',
    preview: {
      movio: 'https://static.heygencdn.com/voice_preview/VRz9yRAwKEaeafHP6Vfzu7.wav',
    },
    settings: {
      style: 'cheerful',
      elevenlabs_settings: null,
    },
    ssml: {
      style: [],
      lang: [],
      break: true,
      prosody: ['rate', 'pitch'],
      emphasis: 'none',
      say_as: [],
    },
    is_customer: false,
    is_favorite: false,
    is_paid: false,
    support_realtime: true,
  },
  {
    voice_id: 'beaa640abaa24c32bea33b280d2f5ea3',
    labels: ['Youth', 'Audiobooks', 'E-learning', 'Narration'],
    language: 'English',
    flag: 'https://static.heygencdn.com/region_flags/us.png',
    locale: 'en-US',
    sort: 16,
    gender: 'Male',
    tags: 'Young Adult, Ads, Explainer Videos, E-learning & Presentations',
    display_name: 'Johan - Friendly',
    preview: {
      movio: 'https://static.heygencdn.com/voice_preview/fkxNCfdkoKfopBpTtvQqAp.wav',
    },
    settings: {
      style: 'hopeful',
      elevenlabs_settings: null,
    },
    ssml: {
      style: [],
      lang: [],
      break: true,
      prosody: ['rate', 'pitch'],
      emphasis: 'none',
      say_as: [],
    },
    is_customer: false,
    is_favorite: false,
    is_paid: false,
    support_realtime: true,
  },
  {
    voice_id: 'c089f9832fd04922b34b3d2f3661d113',
    labels: ['Youth', 'E-learning', 'Explainer', 'Narration'],
    language: 'English',
    flag: 'https://static.heygencdn.com/region_flags/us.png',
    locale: 'en-US',
    sort: 15,
    gender: 'Male',
    tags: 'Young Adult, Ads, Explainer Videos, E-learning & Presentations',
    display_name: 'Brandon - Warm',
    preview: {
      movio: 'https://static.heygencdn.com/voice_preview/maqA9fw7siQAcv2WafDz4F.wav',
    },
    settings: {
      style: '',
      elevenlabs_settings: null,
    },
    ssml: {
      style: [],
      lang: [],
      break: true,
      prosody: ['rate', 'pitch'],
      emphasis: 'none',
      say_as: [],
    },
    is_customer: false,
    is_favorite: false,
    is_paid: false,
    support_realtime: true,
  },
  {
    voice_id: 'c2958d67f1e74403a0038e3445d93d50',
    labels: ['Youth', 'E-learning', 'Audiobooks', 'Explainer'],
    language: 'English',
    flag: 'https://static.heygencdn.com/region_flags/us.png',
    locale: 'en-US',
    sort: 14,
    gender: 'Female',
    tags: 'Young Adult, Ads, Explainer Videos, E-learning & Presentations',
    display_name: 'Sherry - Friendly',
    preview: {
      movio: 'https://static.heygencdn.com/voice_preview/RGqs3H9eLfHkc3HduJXxTY.wav',
    },
    settings: {
      style: 'friendly',
      elevenlabs_settings: null,
    },
    ssml: {
      style: [],
      lang: [],
      break: true,
      prosody: ['rate', 'pitch'],
      emphasis: 'none',
      say_as: [],
    },
    is_customer: false,
    is_favorite: false,
    is_paid: false,
    support_realtime: true,
  },
  {
    voice_id: 'cc29d03937d14240acf109c827a9a51a',
    labels: ['Youth', 'Narration', 'E-learning'],
    language: 'English',
    flag: 'https://static.heygencdn.com/region_flags/us.png',
    locale: 'en-US',
    sort: 10,
    gender: 'Female',
    tags: 'Young Adult, Explainer Videos, E-learning & Presentations, Product demos',
    display_name: 'Aria - Newscaster',
    preview: {
      movio: 'https://static.heygencdn.com/voice_preview/5vzP2xA79TcGpndVngHBbA.wav',
    },
    settings: {
      style: 'narration-professional',
      elevenlabs_settings: null,
    },
    ssml: {
      style: [],
      lang: [],
      break: true,
      prosody: ['rate', 'pitch'],
      emphasis: 'none',
      say_as: [],
    },
    is_customer: false,
    is_favorite: false,
    is_paid: false,
    support_realtime: true,
  },
  {
    voice_id: 'd7bbcdd6964c47bdaae26decade4a933',
    labels: ['Middle-Aged', 'E-learning', 'Audiobooks'],
    language: 'English',
    flag: 'https://static.heygencdn.com/region_flags/us.png',
    locale: 'en-US',
    sort: 4,
    gender: 'Male',
    tags: 'Middle-Aged, Explainer Videos, News',
    display_name: 'Christopher - Calm',
    preview: {
      movio: 'https://static.heygencdn.com/voice_preview/Pn2tXVGjpwyHpWTsKFj87X.wav',
    },
    settings: {
      style: '',
      elevenlabs_settings: null,
    },
    ssml: {
      style: [],
      lang: [],
      break: true,
      prosody: ['rate', 'pitch'],
      emphasis: 'none',
      say_as: [],
    },
    is_customer: false,
    is_favorite: false,
    is_paid: false,
    support_realtime: true,
  },
  {
    voice_id: 'ec4aa6ac882147ffb679176d49f3e41f',
    labels: ['Middle-Aged', 'E-learning', 'Explainer'],
    language: 'English',
    flag: 'https://static.heygencdn.com/region_flags/us.png',
    locale: 'en-US',
    sort: 12,
    gender: 'Male',
    tags: 'Young Adult, Ads',
    display_name: 'Eric - Newscaster',
    preview: {
      movio: 'https://static.heygencdn.com/voice_preview/QyfEredcYX3MKGkBGudZ9H.wav',
    },
    settings: {
      style: '',
      elevenlabs_settings: null,
    },
    ssml: {
      style: [],
      lang: [],
      break: true,
      prosody: ['rate', 'pitch'],
      emphasis: 'none',
      say_as: [],
    },
    is_customer: false,
    is_favorite: false,
    is_paid: false,
    support_realtime: true,
  },
  {
    voice_id: 'f7658a75545d4b70b04d8784c07bd038',
    labels: ['Youth', 'E-learning', 'Ads'],
    language: 'English',
    flag: 'https://static.heygencdn.com/region_flags/us.png',
    locale: 'en-US',
    sort: 11,
    gender: 'Male',
    tags: 'Young Adult, News, Explainer Videos',
    display_name: 'Lucas - Natural',
    preview: {
      movio: 'https://static.heygencdn.com/voice_preview/9ex83FXgouLw6NVytasyH7.wav',
    },
    settings: {
      style: 'newscast',
      elevenlabs_settings: null,
    },
    ssml: {
      style: [],
      lang: [],
      break: true,
      prosody: ['rate', 'pitch'],
      emphasis: 'none',
      say_as: [],
    },
    is_customer: false,
    is_favorite: false,
    is_paid: false,
    support_realtime: true,
  },
  {
    voice_id: 'fd6bf3b9c3254137aefbe36972c39349',
    labels: ['Youth', 'Narration', 'Explainer', 'E-learning'],
    language: 'English',
    flag: 'https://static.heygencdn.com/region_flags/us.png',
    locale: 'en-US',
    sort: 20,
    gender: 'Female',
    tags: 'Young Adult, Ads, Explainer Videos, E-learning & Presentations',
    display_name: 'Jane - Serious',
    preview: {
      movio: 'https://static.heygencdn.com/voice_preview/iuocs4hoQUGTHJoLnzYYyf.wav',
    },
    settings: {
      style: 'unfriendly',
      elevenlabs_settings: null,
    },
    ssml: {
      style: [],
      lang: [],
      break: true,
      prosody: ['rate', 'pitch'],
      emphasis: 'none',
      say_as: [],
    },
    is_customer: false,
    is_favorite: false,
    is_paid: false,
    support_realtime: true,
  },
  {
    voice_id: 'ff465a8dab0d42c78f874a135b11d47d',
    labels: ['Older', 'Audiobooks', 'Narration'],
    language: 'English',
    flag: 'https://static.heygencdn.com/region_flags/us.png',
    locale: 'en-US',
    sort: 21,
    gender: 'Male',
    tags: 'Middle-Age,E-learning & Presentations, Product demos, Explainer Videos, News, Ads',
    display_name: 'Davis - Professional',
    preview: {
      movio: 'https://static.heygencdn.com/voice_preview/MJy76NRegZK6zmnSzSn7qb.wav',
    },
    settings: {
      style: 'general',
      elevenlabs_settings: null,
    },
    ssml: {
      style: [],
      lang: [],
      break: true,
      prosody: ['rate', 'pitch'],
      emphasis: 'none',
      say_as: [],
    },
    is_customer: false,
    is_favorite: false,
    is_paid: false,
    support_realtime: true,
  },
];

module.exports = {
  voices,
};
